# ansible-playbook -i ./hosts MYSERVERCENTOS.yml -K
# sudo ansible-playbook -i 192.168.178.1, MYSERVERCENTOS.yml -K -k
# Get MY IP ADRESS!11!121121212131eurw	asfawsbfsxz hbjszjcvzxjhcvsZBHDCdsCvjkasdcvwz

---
- hosts: localhost
  become: yes
  tasks:
    - name: upgrade all packages
      yum:
        name: "*"
        state: latest

    - name: Install packages
      yum:
        name:
          - dnf-automatic
          - ansible
          - vim
          - yum-utils
          - python3
          - setroubleshoot
          - autofs
          - cronie
        state: latest

    - name: Start service dnf-automatic.timer, if not started
      service:
        name: dnf-automatic.timer
        state: started

    - name: Enable service dnf-automatic.timer, and not touch the state
      service:
        name: dnf-automatic.timer
        enabled: yes

    - name: Applying automatic updates.
      lineinfile: dest=/etc/dnf/automatic.conf
        regexp="^apply_updates = no"
        line="apply_updates = yes"
        state=present
      notify: Restart dnf-automatic.timer

    - name: Do nothing when laptop lid is closed
    - lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#HandleLidSwitch=suspend"
        state: present
        line: "HandleLidSwitch=ignore"
        notify: Restart systemd-logind

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication yes"
        line="PasswordAuthentication no"
        state=present
      notify:

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^#PermitRootLogin yes"
        line="PermitRootLogin no"
        state=present
      notify: Restart sshd
